server:
  port: 8085

api:
  finnhub:
    domain: "finnhub.io"
    endpoints:
      profile2: "/api/v1/stock/profile2"
      quote: "/api/v1/quote"
      token: "ck4ffbpr01qus81pv1u0ck4ffbpr01qus81pv1ug"

spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: 'postgres'
  password: Rw789456
spring.jpa:
  show-sql: true
  ## Hiberate Properties
  properties.hiberate.dialect: org.hiberate.dialect.PostgreSQLDialect
  # Hiberate ddl auto (create, create-drop, validate, update)
  hiberate.ddl-auto: validate #update

spring.sql.init:
  # schema-locations: classpath:ddl/DDL_DROPS.sql, classpath:ddl/DDL_TUSERS.sql
  mode: always #always
